### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by NewIncome**
Feature branch with commits for whole Embedded youtube video project.
Created Navigation bar with search-bar inside, search-buttons.
Created Video with title, number of views.
Created sidebar with related videos with views for each one.
Created files for linter configuration.

### CODE REVIEW

**Comment by alissonperes** [comment]
Made the correcitons in linter from stickler. No more errors found.

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work :clap: . However, You still need to make some changes in order for us to approve your project. check below :arrow_down: 

- **[REQUIRED]** I see that you used bootstrap in this project. Please use regular css for this project :nerd_face: , the use of bootstrap is forbidden in this project. :no_entry_sign:  

#### Page structure

##### Video

* [x] It shows the avatar of the user who uploaded the video
* [x] It has a subscribe button

### That's it guys :relaxed: . When finished implementing the above, kindly submit another code review from :pray: .

**Review by wathigo — APPROVED** [review]
## You may move on :rocket: 

**Congratulations, your project meets all the requirements.**

_Good luck in your future projects_

**Pull request merged**
